language: go

go:
 - 1.10.3
 - tip

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/stretchr/testify/assert
  
install:
  - go get -d ./...

script: ./scripts/test.sh

notifications:
  email: false
